@startuml

actor/ "Universidad / administrador institucional" <<Business Actor>> as Admin

rectangle "Modelo de Casos de Uso del Negocio - EduVerify" {
    usecase/ "Configurar institucion educativa" as UC2
    usecase/ "Gestionar usuarios institucionales" as UC3
}

Admin --> UC2
UC2 --> UC3 : <<include>>


skinparam usecase {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
  StereotypeFontColor #2E7D32
}
skinparam actor {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
  StereotypeFontColor #2E7D32
}
skinparam Arrow {
  Color #7A1631
}

@enduml
