@startuml

actor/ "Docente" <<Business Actor>> as Docente

rectangle "Modelo de Casos de Uso del Negocio - EduVerify" {
    usecase/ "Gestionar alertas e incidencias" as UC9
    usecase/ "Visualizar dashboard de supervision" as UC15
    usecase/ "Reportar plagio de estudiante" as UC11
    usecase/ "Visualizar evidencia de incidencia" as UC17
    usecase/ "Generar reporte de incidencias" as UC12
}

Docente --> UC15

UC15 --> UC17 : <<include>>
UC15 --> UC9 : <<extend>>
UC17 --> UC11 : <<extend>>
UC15 --> UC12 : <<extend>>

skinparam usecase {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
  StereotypeFontColor #2E7D32
}
skinparam actor {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
  StereotypeFontColor #2E7D32
}
skinparam Arrow {
  Color #7A1631
}

@enduml
